name: Selenium Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  Selenium-Tests:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Install Chrome
      run: |
        $progressPreference = 'SilentlyContinue'
        Invoke-WebRequest "https://dl.google.com/chrome/install/latest/chrome_installer.exe" -OutFile "chrome_installer.exe"
        Start-Process -FilePath "chrome_installer.exe" -Args "/silent /install" -Wait
        Remove-Item "chrome_installer.exe"

    - name: Run tests with reporting
      run: |
        New-Item -ItemType Directory -Path TestResults -Force
        dotnet test --configuration Release --no-build --verbosity normal `
          --logger "trx;LogFileName=test-results.trx" `
          --logger "html;LogFileName=test-results.html" `
          --results-directory TestResults

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: TestResults/
