name: Selenium Tests

on:
  workflow_dispatch:
    inputs:
      test-type:
        description: 'Type of tests to run'
        required: false
        default: 'all'
        type: choice
        options:
        - all
        - smoke
        - regression
        - integration
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  run-tests:
    runs-on: windows-latest
    env:
      TEST_FILTER: ${{ github.event.inputs.test-type != 'all' && format('Category={0}', github.event.inputs.test-type) || '' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Install Chrome
      run: |
        $progressPreference = 'SilentlyContinue'
        Invoke-WebRequest "https://dl.google.com/chrome/install/latest/chrome_installer.exe" -OutFile "chrome_installer.exe"
        Start-Process -FilePath "chrome_installer.exe" -Args "/silent /install" -Wait
        Remove-Item "chrome_installer.exe"

    - name: Run tests
      run: |
        $filter = "${{ env.TEST_FILTER }}"
        Write-Host "Filter: $filter"
        
        if ($filter) {
            dotnet test --configuration Release --no-build --verbosity normal `
              --filter "$filter" `
              --logger "trx;LogFileName=test-results.trx" `
              --logger "html;LogFileName=test-results.html" `
              --results-directory TestResults
        } else {
            dotnet test --configuration Release --no-build --verbosity normal `
              --logger "trx;LogFileName=test-results.trx" `
              --logger "html;LogFileName=test-results.html" `
              --results-directory TestResults
        }

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: TestResults/
