name: Selenium Tests

on:
  workflow_dispatch:
    inputs:
      test-type:
        description: 'Type of tests to run'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - smoke
          - regression
          - integration

jobs:
  run-tests:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Install Chrome
      run: |
        $progressPreference = 'SilentlyContinue'
        Invoke-WebRequest "https://dl.google.com/chrome/install/latest/chrome_installer.exe" -OutFile "chrome_installer.exe"
        Start-Process -FilePath "chrome_installer.exe" -Args "/silent /install" -Wait
        Remove-Item "chrome_installer.exe"

    - name: Create TestResults directory
      run: |
        New-Item -ItemType Directory -Path TestResults -Force
        Write-Host "TestResults directory created/cleaned"

    - name: Run tests with detailed reporting
      run: |
        $testType = "${{ github.event.inputs.test-type }}"
        Write-Host "Test type selected: $testType"
        
        if ($testType -eq "all") {
          Write-Host "Running all tests with detailed reporting"
          dotnet test --configuration Release --no-build --verbosity normal `
            --logger "trx;LogFileName=test-results.trx" `
            --logger "html;LogFileName=test-results.html" `
            --results-directory TestResults
        } else {
          Write-Host "Running $testType tests with detailed reporting"
          dotnet test --configuration Release --no-build --verbosity normal `
            --filter "Category=$testType" `
            --logger "trx;LogFileName=test-results-$testType.trx" `
            --logger "html;LogFileName=test-results-$testType.html" `
            --results-directory TestResults
        }

    - name: List generated test files
      if: always()
      run: |
        Write-Host "📁 Contents of TestResults directory:"
        Get-ChildItem -Path TestResults -Recurse | ForEach-Object {
          Write-Host "  - $($_.Name) ($($_.Length) bytes)"
        }

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ github.event.inputs.test-type }}-${{ github.run_number }}
        path: TestResults/
        retention-days: 7
